### PR TITLE
fix nodejs 0.10 Promises issue

### PR DESCRIPTION
**Pull request by iamstarkov**

### CODE REVIEW

**Comment by floatdrop** [comment]
Tests should get Promise polyfill from Babel runtime. See [loud-rejection fixture](https://github.com/sindresorhus/ava/blob/master/test/fixture/loud-rejection.js#L4) in ava for example.

**Comment by floatdrop** [comment]
@iamstarkov probably you want just pass `Promise` object to [`pify` calls](https://github.com/iamstarkov/generator-nm/blob/b504bdbe0748c2847ce7798169720124817ae112/test.js#L50) - this should work fine.

**Comment by sindresorhus** [comment]
@iamstarkov I commented in the chat that I was fixing this. I went with just dropping Node.js 0.10 support.

**Comment by iamstarkov** [comment]
it’s good. I just wanted to try to fix it on my own

**Pull request closed without merging**
