### PR TITLE
add moduleDescription

### PR DESCRIPTION
**Pull request by revolunet**
handy

### CODE REVIEW

**Comment by arthurvr** [comment]
Now you just added the prompt but it's used nowhere. I personally am :-1: for this feature. I mostly find it easier to give the description after building the module instead of when scaffolding it. Oftentimes I change my mind about how a module should look when writing tests, for example.

**Comment by revolunet** [comment]
it fills the package.json template from the boilerplate, isnt it ?

**Comment by arthurvr** [comment]
> it fills the package.json template from the boilerplate, isnt it ?

[No](https://github.com/sindresorhus/generator-nm/blob/master/app/templates/_package.json#L4). We maintain a different version of the boilerplate here so you'll have to update the boilerplate here too.

**Comment by revolunet** [comment]
Ho sorry, thought the other boilerplate was a direct dependency...

So you think its useless to ask for the module description on init ? or should i fix the PR with the modified var in the template ?

**Comment by sindresorhus** [comment]
I dunno. I explicitly left it out as I never know what the description of a module would be up front. Let me think about it.

**Comment by sindresorhus** [comment]
While it might be handy for some, neither I or anyone I know (I asked around) writes the description up-front, so I'm going to pass on this. Thanks for the suggestions though. Happy to consider other improvement :)

**Comment by revolunet** [comment]
ok no worry, thanks :)

**Pull request closed without merging**
