### PR TITLE
Add eslintrc generation

### PR DESCRIPTION
**Pull request by btd**

### CODE REVIEW

**Comment by stevemao** [comment]
@btd 
I don't think @sindresorhus is interested in this as this is probably supposed to be minimum. https://github.com/yeoman/generator-node/issues/66 They should be so maybe create a PR there?

**Comment by btd** [comment]
Yep @stevemao i already understand it) I just locally use my patched version. I do not think they will add it also.

**Comment by stevemao** [comment]
@btd Why? They mentioned eslint there. But I think it'll be lower priority but they will eventually support it.

**Comment by btd** [comment]
@stevemao because of this cite:

> jshint (we also have eslint on yeoman-generator, but we'll make a cut and probably keep only one)

Actually i think i will do own generator with some more options.

**Comment by sindresorhus** [comment]
I'm planning to support ESLint. Just not ready to do it quite yet.

**Pull request closed without merging**
