### PR TITLE
compose with generator-travis

### PR DESCRIPTION
**Pull request by iamstarkov**
What do you think about composing nm and travis generators? You are no longer will need to handle travis config on your own.

for example current update will bring nodejs 4 support

### CODE REVIEW

**Comment by sindresorhus** [comment]
Would be a good idea for a larger generator, but I prefer to handle it manually here, for simplicity and being in control. I also plan on having a separate .travis.yml file depending on the prompts.

Happy to use it in our [official Yeoman generators](https://github.com/yeoman/). Hint hint.

**Comment by iamstarkov** [comment]
will try my luck with yeoman/generator-node#176

**Comment by iamstarkov** [comment]
Some news about generator-travis:

* it extends existing travis config, not overwrites.
* it merged into generator-node =)
* it got LTS-supported nodejs versions list, I found [this your answer](https://github.com/sindresorhus/ama/issues/250#issuecomment-145645283) as a best solution to choose which versions to keep in config.

**Comment by iamstarkov** [comment]
with all these changes about LTS in [generator-travis](https://www.npmjs.com/package/generator-travis) do you still want to maintain `.travis.yml` on your own?

**Pull request closed without merging**
