### PR TITLE
fix #3 : Changed the initial prefix files name, . to _

### LINKED ISSUE #3: Npm package doesn't contain all files
The package published to npm does not contain all the files.

The contents of templates is:

 - _package.json 
 - index.js
 - license
 - readme.md
 - test.js

### PR DESCRIPTION
**Pull request by eduardoroyer**

### CODE REVIEW

**Comment by eduardoroyer** [comment]
The error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Only on iojs. Why does it occurs?

**Comment by kevva** [comment]
Hm, it already works for me when installing directly from GitHub or npm.

**Comment by eduardoroyer** [comment]
Does the best solution is installing from github?

**Comment by kevva** [comment]
It works from npm too.

**Comment by eduardoroyer** [comment]
Do you have a Macbook? I tested in a ubuntu 14.04 and in a windows 7 and isn't working.

**Comment by kevva** [comment]
screenshot

**Comment by arthurvr** [comment]
I am having troubles as well. Installed from npm, io.js 1.5.1.

```sh
arthurvr at iMac in ~/code/jquery/api.jquery.com on master [+!]
$ npm i -g generator-nm
generator-nm@1.0.0 /Users/arthurvr/.nvm/versions/io.js/v1.5.1/lib/node_modules/generator-nm
├── humanize-url@1.0.1 (strip-url-auth@1.0.0)
├── normalize-url@1.2.0 (sort-keys@1.0.0, object-assign@2.0.0, query-string@1.0.0, prepend-http@1.0.1)
├── superb@1.1.3 (unique-random-array@1.0.0, meow@3.1.0)
└── yeoman-generator@0.18.10 (read-chunk@1.0.1, detect-conflict@1.0.0, dargs@3.0.1, yeoman-welcome@1.0.1, xdg-basedir@1.0.1, user-home@1.1.1, rimraf@2.3.2, diff@1.3.1, class-extend@0.1.1, pretty-bytes@1.0.3, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.0, debug@2.1.3, nopt@3.0.1, cross-spawn@0.2.6, chalk@1.0.0, istextorbinary@1.0.2, yeoman-assert@1.0.0, run-async@0.1.0, mem-fs-editor@1.2.2, mkdirp@0.5.0, shelljs@0.3.0, dateformat@1.0.11, cli-table@0.3.1, through2@0.6.3, github-username@1.1.1, glob@4.5.3, findup-sync@0.2.1, file-utils@0.2.2, lodash@2.4.1, gruntfile-editor@0.2.0, download@3.3.0, cheerio@0.18.0, sinon@1.14.1, yeoman-environment@1.2.4, inquirer@0.8.2)

arthurvr at iMac in ~/code/jquery/api.jquery.com on master [+!]
$ ls -al /Users/arthurvr/.nvm/versions/io.js/v1.5.1/lib/node_modules/generator-nm/app/templates/
total 80
drwxr-xr-x  12 user  staff   408 Mar 23 13:14 .
drwxr-xr-x   4 user  staff   136 Mar 23 13:14 ..
-rw-r--r--   1 user  staff   231 Feb  9 19:30 .editorconfig
-rw-r--r--   1 user  staff    12 Apr  1  2014 .gitattributes
-rw-r--r--   1 user  staff   170 Mar 14 06:03 .jshintrc
-rw-r--r--   1 user  staff    13 Apr 28  2013 .npmignore
-rw-r--r--   1 user  staff    72 Feb  8 10:53 .travis.yml
-rw-r--r--   1 user  staff   502 Mar 14 06:44 _package.json
-rw-r--r--   1 user  staff   210 Mar 14 06:11 index.js
-rw-r--r--   1 user  staff  1114 Mar 14 06:56 license
-rw-r--r--   1 user  staff   649 Mar 14 06:39 readme.md
-rw-r--r--   1 user  staff   203 Mar 14 06:35 test.js

**Comment by eduardoroyer** [comment]
The files are there, but when I execute `yo nm`, he doesn't find these files

**Comment by kevva** [comment]
@SBoudrias, is this expected?

**Comment by kevva** [comment]
Nevermind, just saw that the `.gitignore` file isn't published with npm. @eduardoroyer, instead of prefixing them with `_`, could you just remove the `.` instead?

**Comment by eduardoroyer** [comment]
Ok, take a second

**Comment by kevva** [comment]
Could you squash them too? :)

**Comment by eduardoroyer** [comment]
What do you want to say with 'squash them' ?

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/generator-nm/commit/01eb1d547faa1ff3a4808390c164f8918be9b01e.

**Comment by arthurvr** [comment]
> What do you want to say with 'squash them' ?

@eduardoroyer He meant to squash the commits.

**Pull request closed without merging**
