### PR TITLE
implement git init from the start

### PR DESCRIPTION
**Pull request by iamstarkov**
I found that it’s not git repo after generator finished work, so I added tests, integrate [git-init](https://github.com/iamstarkov/generator-git-init) into _nm_ and that’s pretty much it.

### CODE REVIEW

**Comment by iamstarkov** [comment]
=( i don’t know why it’s failing on 0.10, while previous build are 0.10 okay-ish

**Comment by iamstarkov** [comment]
I checked current master on 0.10 in #32 and its not working at all. should I remove 0.10 from travis config, @sindresorhus?

**Comment by sindresorhus** [comment]
I think it's a bit overkill to compose something as simple as this. I went with just adding it directly to the generator. Thanks though :)

**Comment by iamstarkov** [comment]
happy end 🦄

**Pull request closed without merging**
